app/urls.py
from django.urls import path, re_path

from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from . import views

from .views import *

urlpatterns = [
	path('', Index.as_view(), name='index'),
	path('signup', views.register_user, name='signup'),
	path('login', Login.as_view(), name='login'),
	path('logout', auth_views.LogoutView.as_view(next_page='index'), name='logout'),
	path('api/users/<str:user_id>', UsernameCheck.as_view(), name='username_check'),
	path('activate/<str:uidb64>/<str:token>', views.activate, name='activate'),
	path('password_reset_request/', PasswordReset.as_view(), name='password_reset_request'),
	path('password_reset_request_done/', PasswordResetDone.as_view(), name='password_reset_done'),
	path('password_reset_confirm/<uidb64>/<token>', PasswordResetConfirm.as_view(), name='password_reset_confirm'),
	path('password_reset_complete/', PasswordResetComplete.as_view(), name='password_reset_complete'),
	path('forums/', Forums.as_view(), name='forums'),
	path('forums/<str:order>', Forums.as_view(), name="forums-ordered"),
	path('forums/<int:pk>/', ForumDetail.as_view(), name="thread-detail"),
	path('forums/<int:pk>/like', login_required(ForumLike.as_view()), name="forum-like"),
	path('forums/<int:pk>/dislike', login_required(ForumDislike.as_view()), name="forum-dislike"),
	path('forums/<int:pk>/removeLike', login_required(ForumRemoveLike.as_view()), name="forum-removelike"),
	path('forums/<int:pk>/removeDislike', login_required(ForumRemoveDislike.as_view()), name="forum-removedislike"),
	path('forums/<int:pk>/view', ForumView.as_view(), name="forum-view"),
	path('threads/api/delete_thread', ThreadDeleteView.as_view(), name="thread_delete"),
	path('threads/api/delete_comment', ThreadCommentDeleteView.as_view(), name="thread_comment_delete"),
	path('youtube_token', views.youtube_token_v, name='get_youtube_token'),	
	path('profile', login_required(views.update_profile), name="profile"),
	path('experiences', ExperiencesView.as_view(), name="experiences"),
	path('contact-us', ContactUsView.as_view(), name="contact-us"),
	path('about-us', AboutUsView.as_view(), name="about-us"),
	path('send_email', views.ContactUsSendEmail, name="contact_us_send_email"),
	path('document', DocumentView.as_view(), name="document"),
	path('experiences/manage', ManageExperiencesView.as_view(), name="experiences_manage"),
	path('experiences/modify', ModifyExperienceStatus.as_view(), name="experiences_modify"),
	path('experiences/api/pendingexperiences', PendingExperiences.as_view(), name="experiences_pending"),
	path('experiences/api/delete_experience', DeleteExperienceView.as_view(), name="delete_experience"),
	path('experiences/create', CreateExperience.as_view(), name="experiences_create"),
	path('experiences/<int:pk>/', ExperienceDetailView.as_view(), name="experience-detail"),
	path('experiences/<str:order>', ExperiencesOrdered.as_view(), name="experiences-ordered"),
	path('experiences/<int:pk>/like', login_required(ExperienceLike.as_view()), name="experience-like"),
	path('experiences/<int:pk>/dislike', login_required(ExperienceDislike.as_view()), name="experience-dislike"),
	path('experiences/<int:pk>/removeLike', login_required(ExperienceRemoveLike.as_view()), name="experience-removelike"),
	path('experiences/<int:pk>/removeDislike', login_required(ExperienceRemoveDislike.as_view()), name="experience-removedislike"),
	path('myforums/', login_required(MyForumsView.as_view()), name="my-forums"),
	path('myexperiences/', login_required(MyExperiencesView.as_view()), name="my-experiences"),
	path('experiences/<int:pk>/view', ExperienceView.as_view(), name="experience-view"),
	path('mycomments/', login_required(MyCommentsView.as_view()), name="my-comments"),
	path('box', login_required(BoxView.as_view()), name="box"),
	path('guide_general/<int:pk>', login_required(GuideView.as_view()), name="guides"),
	path('crossword', CrossWordView.as_view(), name="crossword"),
	path('search', SearchView.as_view(), name="search"),
	path('guides/addAnswer', AddAnswerView.as_view(), name="add_answer"),
	path('guides/addReview', AddToolboxReview.as_view(), name="add_review"),
	path('guides/manage', ManageToolboxesView.as_view(), name="toolboxes_manage"),
	path('guides/comment/<str:user_id>/<str:tb_id>', CommentToolboxView.as_view(), name="toolbox_comment"),
	path('guides/view_comment/<str:tb_id>', ViewToolboxCommentView.as_view(), name="view_toolbox_comment"),
	path('toolbox/api/comment', ToolboxAddCommentApiView.as_view(), name="addtbxcomment")
]

convivetic/urls.py
from django.contrib import admin
from django.urls import path, include
from app import views as app_views
from django.conf.urls import handler404, handler403

handler404 = app_views.handler404
handler403 = app_views.handler403

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import date

PERSON_TITLE_CHOICES = [
	('Don', 'Don'),
	('Doña', 'Doña'),
	('Señor', 'Señor'),
	('Señora', 'Señora'),
	('Señorita', 'Señorita')
]

GENDER_CHOICES = [
	('M', 'Masculino'),
	('F', 'Femenino')
]

YES_NO_CHOICES = [
	(True, 'Si'),
	(False, 'No')
]

STATUS_CHOICES = [
	('P', 'Pendiente'),
	('A', 'Aprobado'),
	('R', 'Rechazado')
]

TEMPLATE_CHOICES = [
	('TEMP_INTRO', 'TEMP_INTRO'),
	('TEMP_TEST', 'TEMP_TEST'),
	('TEMP_TEST_IMAGE', 'TEMP_TEST_IMAGE'),
	('TEMP_TEXT', 'TEMP_TEXT'),
	('TEMP_ACTIVITY', 'TEMP_ACTIVITY'),
	('TEMP_TEST_MULTIPLE', 'TEMP_TEST_MULTIPLE'),
	('TEMP_CROSSWORD', 'TEMP_CROSSWORD'),
	('TEMP_FILL_THE_BLANKS', 'TEMP_FILL_THE_BLANKS')	
]

class UserProfile(models.Model):
	user = models.OneToOneField(
		User,
		on_delete=models.CASCADE
	)
	title = models.CharField(
		choices = PERSON_TITLE_CHOICES,
		max_length = 50,
		blank=False,
		default='Don'
	)
	birth_date = models.DateField(
		null = True,
		blank = True
	)
	gender = models.CharField(
		choices = GENDER_CHOICES,
		max_length = 50,
		blank=False,
		default='M'
	)
	nationality = models.CharField(
		max_length = 50
	)
	country_of_residence = models.CharField(
		max_length = 50
	)
	phone_number = models.CharField(
		max_length = 15,
		blank = True,
		null=True
	)
	bio = models.TextField(
		default="",
		blank=True,
		null=True
	)
	is_conflict_participant = models.BooleanField(
		default=False,
		choices=YES_NO_CHOICES
	)
	is_conflict_victim = models.BooleanField(
		default=False,
		choices=YES_NO_CHOICES
	)
	is_living_in_conflict_zone = models.BooleanField(
		default=False,
		choices=YES_NO_CHOICES
	)

class ThreadTag(models.Model):
	name = models.CharField(max_length=20)

class Thread(models.Model):
	author = models.ForeignKey(
		User,
		on_delete=models.SET_NULL,
		null=True
	)
	title = models.CharField(
		max_length=100,
		blank=False,
		null=False
	)
	description = models.TextField(
		default='',
		blank=False,
		null=False
	)
	pub_date = models.DateField(
		default=date.today
	)
	video_url = models.CharField(
		max_length=50,
		null=True,
		blank=True
	)
	audio_url = models.CharField(
		max_length=100,
		null=True,
		blank=True
	)
	img = models.ImageField(
		upload_to="uploads/",
		null=True,
		blank=True
	)
	status = models.CharField(
		max_length = 20,
		choices = STATUS_CHOICES,
		default = 'P'
	)
	views = models.PositiveIntegerField(
		default = 0
	)	
	tags = models.ManyToManyField(ThreadTag, blank=True)


class Like(models.Model):
	thread = models.ForeignKey(
		Thread,
		on_delete=models.CASCADE
	)
	author = models.ForeignKey(
		User,
		on_delete=models.SET_NULL,
		null=True
	)

class Dislike(models.Model):
	thread = models.ForeignKey(
		Thread,
		on_delete=models.CASCADE
	)
	author = models.ForeignKey(
		User,
		on_delete=models.SET_NULL,
		null=True
	)


class Comment(models.Model):
	thread = models.ForeignKey(
		Thread,
		on_delete=models.CASCADE
	)
	author = models.ForeignKey(
		User,
		on_delete=models.SET_NULL,
		null=True
	)
	content = models.TextField(
		default='',
		blank=False,
		null=False
	)
	pub_date = models.DateField(
		default=date.today
	)
	video_url = models.CharField(
		max_length=50,
		null=True,
		blank=True
	)
	audio_url = models.CharField(
		max_length=100,
		null=True,
		blank=True
	)
	img = models.ImageField(
		upload_to="uploads/",
		null=True,
		blank=True
	)

class ExperienceTag(models.Model):
	name = models.CharField(max_length=20)


class Experience(models.Model):	
	author = models.ForeignKey(
		User,
		on_delete=models.SET_NULL,
		null=True
	)
	title = models.CharField(
		max_length = 100,
		default = ''
	)
	content = models.TextField(
		default="",
		blank=False,
		null=False
	)
	pub_date = models.DateField(
		default=date.today
	)
	video_url = models.CharField(
		max_length=50,
		null=True,
		blank=True
	)
	audio_url = models.CharField(
		max_length=100,
		null=True,
		blank=True
	)
	img = models.ImageField(
		upload_to="uploads/",
		null=True,
		blank=True
	)
	status = models.CharField(
		max_length = 20,
		choices = STATUS_CHOICES,
		default = 'P'
	)
	views = models.PositiveIntegerField(
		default = 0
	)
	likes = models.PositiveIntegerField(
		default = 0
	)
	tags = models.ManyToManyField(ExperienceTag, blank=True)


class ExperiencesLike(models.Model):
	experience = models.ForeignKey(
		Experience,
		on_delete=models.CASCADE
	)
	author = models.ForeignKey(
		User,
		on_delete=models.SET_NULL,
		null=True
	)

class ExperiencesDislike(models.Model):
	experience = models.ForeignKey(
		Experience,
		on_delete=models.CASCADE
	)
	author = models.ForeignKey(
		User,
		on_delete=models.SET_NULL,
		null=True
	)

class Toolbox(models.Model):
	name = models.CharField(
		max_length = 100,
		default = ''
	)
	description = models.CharField(
		max_length = 1000,
		default = ''
	)
	guide_n = models.PositiveIntegerField(
		default = 0
	)

class ToolboxUser(models.Model):
	toolbox = models.ForeignKey(
		Toolbox,
		on_delete = models.CASCADE
	)
	user = models.ForeignKey(
		User,
		on_delete=models.SET_NULL,
		null=True
	)
	comment = models.CharField(
		max_length = 500,
		blank=True,
		default=''
	)

class Question(models.Model):
	q_type = models.CharField(
		max_length = 20,
		choices = TEMPLATE_CHOICES,
		default = 'TEMP_TEST'
	)
	content = models.CharField(
		max_length = 1500,
		default = ''
	)
	content_templ = models.CharField(
		max_length = 1500,
		default = '',
		null=True,
		blank=True
	)
	img = models.CharField(
		max_length = 100,
		default = '',
		null = True,
		blank = True
	)
	title = models.CharField(
		max_length = 100,
		default = '',
		null = True,
		blank = True
	)
	is_html_content = models.BooleanField(
		default = False,
		choices = YES_NO_CHOICES
	)
	correct_answer = models.PositiveIntegerField(
		default = 0,
		null = True,
		blank = True
	)
	required = models.BooleanField(
		default=False,
		choices=YES_NO_CHOICES
	)
	answers_av = models.CharField(
		max_length = 100,
		default = '' ,
		null=True,
		blank=True
	)
	order = models.PositiveIntegerField(
		default = 0
	)
	toolbox = models.ForeignKey(
		Toolbox,
		on_delete=models.CASCADE,
		default=1
	)
	fill_answer = models.CharField(
		max_length = 700,
		default = '',
		null = True,
		blank = True
	)


class Answer(models.Model):
	question = models.ForeignKey(
		Question,
		on_delete=models.CASCADE,
		default=None
	)
	user = models.ForeignKey(
		User,
		on_delete=models.SET_NULL,
		null=True
	)
	answer = models.CharField(
		max_length = 600,
		default = '',
	)
	

class Guide(models.Model):
	pass

app/templates/app/index.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %} 
	<div class="container-fluid p-container" ng-controller="indexController as ixCtrl">
		<section class="exp-section">
			<div class="exp-gra-c">
				<h3 class="border exp-section-title">Experiencias</h3>
				<br>
				<h5 class="exp-section-description">Descubre relatos, vivencias y testimonios que personas han querido compartir en ConviveTIC, y si estás listo, <a href="{% url 'experiences' %}">¡Comparte tu historia!</a></h5>
				<br>
				<div class="experiences-c">

					{% for exp in experiences %}

					<div class="experience">
						{% include 'app/exp_thumbnail.html' %}
						<div class="exp-data">
							<div class="detail-c">
								<div class="popular-data-c">
									<div class="views"><i class="fas fa-eye"></i> {{ exp.views }}</div>
									<div class="likes"><i class="fas fa-thumbs-up"></i> {{ exp.experienceslike_set.count }}</div>
										
								</div>

								<div class="exp-title"><a href="{% url 'experience-detail' exp.id %}">{{exp.title}}</a></div>
								<div class="content-c">
									<p>{{exp.content|striptags}}</p>
								</div>
								<p class="text-muted text-right"><small>{{ exp.pub_date }}</small></p>
								<div class="publisher"><i class="fas fa-user"></i>{{exp.author.get_full_name}}</div>

							</div>
						</div>
					</div>

					{% endfor %}

					{% if messages %}
					    {% for message in messages %}
					    	{% if message.tags == 'success' %}
					    <p style="display:none" ng-init="ixCtrl.successToast('{{ message }}')">{{ message }}</p>
					    	{% endif %}
					    	{% if message.tags == 'info' %}
					    <p style="display:none" ng-init="ixCtrl.infoToast('{{ message }}')">{{ message }}</p>
					    	{% endif %}
					    {% endfor %}
					{% endif %}

				</div>

				<div class="more-exp">
					<a href="{% url 'experiences' %}" >Mostrar todo ({{experiences.count}}) </a>	
				</div>	

			</div>

			
		</section>
		
		<section class="forum-section">

			<div class="for-gra-c">
				<h3 class="border for-section-title">Foros</h3>
				<br>
				<h5 class="for-section-description">Diálogos entre usuarios de ConviveTIC acerca de temas del conflicto. <a href="{% url 'forums' %}">¡Participa!</a></h5>
				<div class="forum-c">
					<div class="forum rounded">

						{% for thread in thread_list %}
							<div class="forum-item">

								<div class="f-image">
									{% include 'app/thread_thumbnail.html' %}
								</div>
								

								<div class="forum-inline">

									<div class="for-data">
										<a href="{% url 'thread-detail' thread.id %}">{{thread.title}}</a>

										<div class="comment-c">
											<i class="far fa-comment"></i>
											<div class="comment-counter">
												{{thread.comment_set.count}}

											</div>
										</div>

									</div>
								

									<div class="forum-publisher">
										<p class="f-date">{{ thread.pub_date }}</p>
										<p class="f-name">{{ thread.author.get_full_name }}</p>
									</div>

								</div>
							</div>

						{% endfor %}
						
					</div>

					<div class="forum rounded">
						{% for thread in secondary_threads %}
							<div class="forum-item">

								<div class="f-image">
									{% include 'app/thread_thumbnail.html' %}
								</div>
								

								<div class="forum-inline">

									<div class="for-data">
										<a href="{% url 'thread-detail' thread.id %}">{{thread.title}}</a>

										<div class="comment-c">
											<i class="far fa-comment"></i>
											<div class="comment-counter">
												
												{{thread.comment_set.count}}

											</div>
										</div>

									</div>
								

									<div class="forum-publisher">
										<p class="f-date">{{ thread.pub_date }}</p>
										<p class="f-name">{{ thread.author.get_full_name }}</p>
									</div>

								</div>
							</div>


						{% endfor %}
						
					</div>

					<div class="f-aside">
						<div class="forum-invitation rounded">
							<h5>¿Te interesa participar en los foros?</h5>

							<p>La discusión es fundamental para la generación de espacios de participación que constribuyan a la inclusión y en general al mejoramiento social.</p>

							<a class="btn btn-primary" href="{% url 'forums' %}">Participar</a>

						</div>

					</div>
				</div>

				<div class="more-forum">
					<a href="{% url 'forums' %}" >Mostrar todo ({{th_quantity}})</a>	
				</div>

				
			</div>
			
		</section>

			
	</div>

	<div class="container-fluid block-expl">
		
		<div class="contact-section">
			<div class="contact-c">
				<div class="left-c">
					<h4>¿Tienes alguna duda o aporte?</h4>
					<p>Transforma la sociedad con tus aportes, comunícate con nosotros.</p>
					<button class="btn btn-primary">Contáctanos</button>
				</div>
				<div class="right-c">
					<img class="rounded" src="{% static 'app/img/img6.jpg' %}">
				</div>
			</div>
		</div>

	</div>


	<div class="container-fluid start-section">
		<div class="start-c">
			<div class="start-content">
				<div class="float-content">
					
					<p>Empieza a contribuir</p>
					<button class="btn btn-primary">Comenzar</button>
				</div>
			</div>
			<div class="start-img">

		</div>

	</div>
	
	
{% endblock %}

 {% block scripts %} 

 	<script type="text/javascript" src="{% static 'app/logic/controllers/indexController.js' %}"></script>

 {% endblock %}

app/templates/app/thread_detail.html
 {% extends 'app/base.html' %}
 {% load static %}
 {% load widget_tweaks %}

 {% block content %}

 <div class="container-fluid gral-df-container">

 	<div class="f-detail-container" ng-controller="forumDetailController as fdCtrl" ng-init="fdCtrl.init({{object.id}}, {{object.like_set.count}},{{object.dislike_set.count}},{{object.views}},'{% url 'forums' %}', '{{like_status}}')">
	 	
		<div class="detail-c">
			<div class="prof-image">
				{% if object.video_url %}
					<img class="rounded-circle" src="https://img.youtube.com/vi/{{object.video_url}}/0.jpg">
				{% elif object.img %}
					<img class="rounded-circle" src="{{object.img.url}}" alt=""></img>
				{% elif object.audio_url %}
					<img class="rounded-circle" src="{% static 'app/img/defaults/audioposts/1.jpeg' %}">
				{% else %}
					<img class="rounded-circle" src="{% static 'app/img/defaults/textposts/1.jpg' %}">
				{% endif %}
			</div>			

			<div class="detail-right">
				<h4>{{object.title}}</h4>
				<p class="forum-date">
					{{object.pub_date}}
				</p>

				<div class="tags">
					<ul>
						{% for tag in object.tags.all %}

						<li class="rounded">{{tag.name}}</li>
					
						{% endfor %}
					
					</ul>
				</div>

				<div>{{object.description|safe}}</div>

				<div class="detail-c-din">

					{% if object.img %}
						<h6><small>Imagen:</small></h6>
						<img src="{{object.img.url}}" alt="" class="rounded thread-det-img">
					{% endif %}

					{% if object.video_url %}
						<iframe width="420" height="315"
							src="https://www.youtube.com/embed/{{object.video_url}}" class="rounded">
						</iframe>
					{% endif %}
					
					{% if object.audio_url %}
						<audio controls>
						  <source ng-init="fdCtrl.extractId('{{object.audio_url}}')" src="http://docs.google.com/uc?export=open&id={[{fdCtrl.audio_id}]}">
							Your browser does not support the audio element.
						</audio> 
					{% endif %}
				</div>				

				{% if request.user == object.author %}

					<hr>
					<div class="forum-status">
						<h4>Eres el creador de este foro</h4>
						<div class="filler"></div>
						<input type="button" class="btn btn-danger rounded" ng-click="fdCtrl.deleteThread()" value="Eliminar">
					</div>
					<hr>

				{% endif %}

				<div class="detail-social-c">
					<div class="social-left">

						<div class="detail-n">
							<div class="forum-likes">
								<div class="thread-like"
								{% if request.user.is_authenticated %}
									ng-click="fdCtrl.vote()" 
									ng-class="{'active' : fdCtrl.likeStatus == fdCtrl.like_like }"
								{% else %}
									data-toggle="tooltip" data-placement="left" title="Para votar debes iniciar sesión"
								{% endif %}
								>

									<i class="fas fa-thumbs-up"></i>

								</div>
								<h5 id="likes">{[{fdCtrl.likes}]}</h5>
							</div>
							<div class="filler"></div>			
							<div class="forum-dislikes">
								<div class="thread-dislike" 
								{% if request.user.is_authenticated %}
									ng-click="fdCtrl.unvote()" 
									ng-class="{'active' : fdCtrl.likeStatus == fdCtrl.like_dislike }"
								{% else %}
									data-toggle="tooltip" data-placement="left" title="Para votar debes iniciar sesión"								
								{% endif %}
								>

									<i class="fas fa-thumbs-down"></i>

								</div>
								<h5 id="dislikes">{[{fdCtrl.dislikes}]}</h5>
							</div>
						</div>						
					</div>

					<div class="social-right">
						<div class="forum-views">
							<i class="fas fa-eye"></i>
							<h5>{[{fdCtrl.views}]}</h5>
						</div>
					</div>
					
				</div>

			</div>

		</div>

		<hr>

		{% if request.user.is_authenticated %}

			{% if messages %}
			    {% for message in messages %}
			    <p style="display:none" ng-init="fdCtrl.successToast('{{ message }}')">{{ message }}</p>
			    {% endfor %}
			{% endif %}

			<div class="d-new-comment">
				<form novalidate ng-class="{ 'was-validated' : fdCtrl.commentClicked }" id="form" name="form" method="POST" enctype='multipart/form-data' >
					{% csrf_token %}
					
					{% render_field form.video_url %}
	 				{% render_field form.audio_url %}
	 				{% render_field form.thread %}

	 				<h5>Dejar un comentario</h5>

					<div class="form-group">
						{% render_field form.content class+='form-control title-input' placeholder=form.content.label ng-model='content' rows="5" %}
						<div class="login-error-messages" ng-messages='form.content.$error' ng-show="fdCtrl.commentClicked">
							<div ng-messages-include="{% static 'app/util/error_messages.html' %}"></div>
						</div>	
					</div>
					<br>
					<div class="media-type-container text-center">
						<p class="text-muted">Tipo de contenido del comentario</p> 
			 			<div class="btn-group" data-toggle="buttons">	 				
			      			<a href="javascript:void(0)" ng-click="fdCtrl.setMediaOption(fdCtrl.option_text)" ng-class="{ 'active' : fdCtrl.mediaOption == fdCtrl.option_text  }" class='btn btn-outline-primary'>Sólo texto</a>
					    	<a href="javascript:void(0)" ng-click="fdCtrl.setMediaOption(fdCtrl.option_video)" ng-class="{ 'active' : fdCtrl.mediaOption == fdCtrl.option_video  }" class='btn btn-outline-primary'>Video</a>
				    		<a href="javascript:void(0)" ng-click="fdCtrl.setMediaOption(fdCtrl.option_audio)" ng-class="{ 'active' : fdCtrl.mediaOption == fdCtrl.option_audio  }" class='btn btn-outline-primary'>Audio</a>
					    	<a href="javascript:void(0)" ng-click="fdCtrl.setMediaOption(fdCtrl.option_img)" ng-class="{ 'active' : fdCtrl.mediaOption == fdCtrl.option_img  }" class='btn btn-outline-primary'>Imagen</a>
						</div>
					</div>
					<br>
					<div class="form-group f-type-data" ng-show='fdCtrl.mediaOption == fdCtrl.option_img' >
						{% render_field form.img class+="filestyle" data-dragdrop="false" data-text="Seleccionar archivo" %}
						<div ng-show="fdCtrl.fileMissingError" class="login-error-messages">
						  	<p>Debes subir un archivo del tipo que seleccionaste</p>
					    </div>
					</div>
					<div class="form-group f-type-data" ng-class="{ 'was-validated' : fdCtrl.publishClicked }" ng-hide="fdCtrl.mediaOption == fdCtrl.option_text || fdCtrl.mediaOption == fdCtrl.option_img">		  
						  <div class="form-group">
						    <input id="mediaFile" type="file" class="filestyle" data-dragdrop="false" data-text="Seleccionar archivo">
						  </div>
						  <div ng-show="fdCtrl.fileMissingError" class="login-error-messages">
						  	<p>Debes subir un archivo del tipo que seleccionaste</p>
						  </div>
					</div>					
					<div class="text-center" ng-show="fdCtrl.isUploading">
						<br>		
						<p>Subiendo: <span id="percent-transferred"></span></p>
						<progress id="upload-progress"></progress>
					</div>					
					<div class="text-center" ng-show="fdCtrl.uploadComplete">	
						<br>		
						<p id="upload-status">Procesando, espera un momento por favor</p>
						<div id="player"></div>
					</div>

	 				<div class="form-group text-center">
						<button class="btn btn-primary" ng-click="fdCtrl.comment()">Comentar</button>
					</div>

				</form>
			</div>

		{% else %}
			<div class="alert alert-info login-info">
				<p>Para votar y comentar debes estar autenticado</p>
				<button class="btn btn-primary" onclick="location.href='/login'">Iniciar Sesión</button>
			</div>

		{% endif %}

		<div class="detail-comments">
			<p>{{object.comment_set.count}} comentarios</p>

			<hr>

			<div class="d-comments">

				{% for c in object.comment_set.all %}

					<div class="rounded d-comment" id="comm{{ c.id }}">
						<div class="comment-header">
							<h6>{{c.author.get_full_name}}</h6>
							<p>{{c.author.nationality}}</p>
						</div>

						<div class="comment-detail">
							{{c.content|safe}}
						</div>

						{% if c.img or c.video_url or c.audio_url %}

						<div class="comment-c-din">

							{% if c.img %}
								<h6><small>Imagen:</small></h6>
								<img src="/media/{{c.img}}" alt="" class="rounded thread-det-img">
							{% endif %}

							{% if c.video_url %}
								<iframe width="420" height="315"
									src="https://www.youtube.com/embed/{{c.video_url}}" class="rounded">
								</iframe>
							{% endif %}
							
							{% if c.audio_url %}
								<audio controls>
								  <source src="http://docs.google.com/uc?export=open&id={[{fdCtrl.extractCId('{{ c.audio_url }}')}]}">
									Your browser does not support the audio element.
								</audio> 
							{% endif %}
						</div>

						{% endif %}

						<div class="comment-footer" ng-init="fdCtrl.loadAudios()">
							<p>{{c.pub_date}}</p>
						</div>

						<br>
						{% if c.author == request.user %}
							<div class="comment-status">														
								<input type="button" class="btn btn-danger btn-sm rounded" ng-click="fdCtrl.deleteComment({{c.id}})" value="Eliminar">&nbsp;
								<h6 class="text-muted">Eres el autor de este comentario</h6>
							</div>
						{% endif %}
					</div>					
					<hr>

				{% endfor %}

				
				
			</div>
		</div>

 	</div>
 	
 </div>

 {% endblock%}

 {% block scripts %} 

	<script src="https://apis.google.com/js/api.js"></script>
    <script src="{% static 'app/util/youtube/cors_upload.js' %}"></script>
 	<script type="text/javascript" src="{% static 'app/logic/controllers/forumDetailCtrl.js' %}"></script>

 {% endblock %}